import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import AuthProvider from '@/contexts/AuthProvider';
import ActiveStatus from '@/components/ActiveStatus';

export const metadata: Metadata = {
  title: 'Messenger Clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <ActiveStatus />
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
};
